package jp.co.sfrontier.ss3.game.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.sfrontier.ss3.game.model.MatchResult;

@Mapper
public interface MatchResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GAME.MATCH_RESULT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	int insert(MatchResult row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GAME.MATCH_RESULT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	int insertSelective(MatchResult row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table GAME.MATCH_RESULT
	 * @mbg.generated  Tue Dec 02 12:03:59 JST 2025
	 */
	MatchResult selectByPrimaryKey(Long matchResultId);

	/**
	 * プレイヤーの対戦履歴を取り出す<br>
	 * 対戦日の新しい順に取り出す
	 * @param attackerId
	 * @returnt 対戦結果が存在しない場合、空のリストを返す
	 */
	List<MatchResult> selectByAttackerId(@Param("attackerId") long attackerId, @Param("gameId") long gameId);

	/**
	 * 1日の最新対戦履歴を取得する<br>
	 * <br>
	 */
	List<MatchResult> selectRecentHistory();
}